AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ポートフォリオサイトのフロントエンド（S3/CloudFront/WAF）のSAMテンプレート

Parameters:
  ProjectName:
    Type: String
    Description: プロジェクト名（リソース名のプレフィックス）
    Default: "portfolio5352"
  CloudFrontDomainName:
    Type: String
    Description: CloudFrontディストリビューションで利用するカスタムドメイン名
    Default: "portfolio.shou-tech.work"
  CloudFrontAcmCertificateArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: CloudFrontで使用するACM証明書ARN（us-east-1で発行されたもの）を格納したSSMパラメータ
    Default: "/acm/mydomain/arn"
  WebAclArnParameterName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: CloudFront用WAF WebACLのARNを格納したSSMパラメータ
    Default: "/portfolio/waf/arn"
  ViewerRequestFunctionVersionArnParameterName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: viewer-request Lambda@Edge 関数バージョンARNを格納したSSMパラメータ
    Default: "/portfolio/ViewerRequestRewriteFunctionVersion/arn"
  Route53HostedZoneId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: "Route53ホストゾーンIDを格納したSSMパラメータ"
    Default: "/Route53/hostzone/id"
  Route53RecordName:
    Type: String
    Description: 作成するサブドメインのFQDN（末尾のドットは不要）
    Default: "portfolio.shou-tech.work"

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-static-site"
      Tags:
        - Key: project
          Value: !Ref ProjectName

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${ProjectName} static site OAI"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Logging:
          Bucket: !GetAtt CloudFrontLogBucket.DomainName
          Prefix: "cloudfront/"
          IncludeCookies: false
        DefaultRootObject: index.html
        Aliases:
          - !Ref CloudFrontDomainName
        WebACLId: !Ref WebAclArnParameterName
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt StaticSiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          LambdaFunctionAssociations:
            - EventType: viewer-request
              IncludeBody: false
              LambdaFunctionARN: !Ref ViewerRequestFunctionVersionArnParameterName
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontAcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
      Tags:
        - Key: project
          Value: !Ref ProjectName

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"
            Action: "s3:GetObject"
            Resource: !Sub "${StaticSiteBucket.Arn}/*"

  CloudFrontLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-cloudfront-logs"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter30Days
            Status: Enabled
            ExpirationInDays: 30
            Prefix: cloudfront/
      Tags:
        - Key: project
          Value: !Ref ProjectName

  CloudFrontLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudFrontLogBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontLogging
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${CloudFrontLogBucket.Arn}/cloudfront/*"
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  StaticSiteBucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectName}/s3/static-site-bucket-name"
      Type: String
      Value: !Ref StaticSiteBucket
      Description: !Sub "${ProjectName} static site bucket name"
      Tags:
        project: !Ref ProjectName

  CloudFrontDistributionIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectName}/cloudfront/distribution-id"
      Type: String
      Value: !Ref CloudFrontDistribution
      Description: !Sub "${ProjectName} CloudFront distribution id"
      Tags:
        project: !Ref ProjectName

  PortfolioAliasRecordA:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFrontDistribution
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !Ref Route53RecordName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  PortfolioAliasRecordAAAA:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFrontDistribution
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !Ref Route53RecordName
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Outputs:
  StaticSiteBucketName:
    Value: !Ref StaticSiteBucket
    Description: 静的サイト用S3バケット名
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
    Description: CloudFrontディストリビューションID
  CloudFrontDistributionDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: CloudFrontディストリビューションのドメイン名
