AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Edge stack (Route53 + CloudFront with origin failover)'

Parameters:
  ProjectName:
    Type: String
    Description: Project name (resource prefix)
    Default: "portfolio5352"
  CloudFrontDomainName:
    Type: String
    Description: CloudFront custom domain name (no trailing dot)
    Default: "portfolio.shou-tech.work"
  CloudFrontAcmCertificateArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: ACM certificate ARN for CloudFront (issued in us-east-1), stored in SSM Parameter Store
    Default: "/acm/mydomain/arn"
  WebAclArnParameterName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: WAF WebACL ARN for CloudFront stored in SSM Parameter Store
    Default: "/portfolio/waf/arn"
  ViewerRequestFunctionVersionArnParameterName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: viewer-request Lambda@Edge function version ARN stored in SSM Parameter Store
    Default: "/portfolio/ViewerRequestRewriteFunctionVersion/arn"
  HostedZoneId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Route53 hosted zone ID stored in SSM Parameter Store
    Default: "/Route53/hostzone/id"
  StaticSiteBucketName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Static site S3 bucket name stored in SSM Parameter Store
    Default: "/portfolio5352/s3/static-site-bucket-name"
  ErrorPageBucketName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Error page S3 bucket name stored in SSM Parameter Store
    Default: "/portfolio5352/error/page/s3/bucket-name"

Resources:
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${ProjectName} edge OAI"

  CloudFrontLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-cloudfront-logs"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter30Days
            Status: Enabled
            ExpirationInDays: 30
            Prefix: cloudfront/
          - Id: DeleteParquetAfter30Days
            Status: Enabled
            ExpirationInDays: 30
            Prefix: cloudfront-parquet/
      Tags:
        - Key: project
          Value: !Ref ProjectName

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${StaticSiteBucketName}/*"

  ErrorPageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ErrorPageBucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${ErrorPageBucketName}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Logging:
          Bucket: !GetAtt CloudFrontLogBucket.DomainName
          Prefix: "cloudfront/"
          IncludeCookies: false
        DefaultRootObject: index.html
        Aliases:
          - !Ref CloudFrontDomainName
        WebACLId: !Ref WebAclArnParameterName
        Origins:
          - Id: ServiceOrigin
            DomainName: !Sub "${StaticSiteBucketName}.s3.${AWS::Region}.amazonaws.com"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
          - Id: ErrorOrigin
            DomainName: !Sub "${ErrorPageBucketName}.s3.${AWS::Region}.amazonaws.com"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        OriginGroups:
          Quantity: 1
          Items:
            - Id: OriginFailover
              FailoverCriteria:
                StatusCodes:
                  Quantity: 6
                  Items:
                    - 403
                    - 404
                    - 500
                    - 502
                    - 503
                    - 504
              Members:
                Quantity: 2
                Items:
                  - OriginId: ServiceOrigin
                  - OriginId: ErrorOrigin
        DefaultCacheBehavior:
          TargetOriginId: OriginFailover
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          LambdaFunctionAssociations:
            - EventType: viewer-request
              IncludeBody: false
              LambdaFunctionARN: !Ref ViewerRequestFunctionVersionArnParameterName
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: /error.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponsePagePath: /error.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 500
            ResponsePagePath: /error.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 502
            ResponsePagePath: /error.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 503
            ResponsePagePath: /error.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 504
            ResponsePagePath: /error.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontAcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
      Tags:
        - Key: project
          Value: !Ref ProjectName

  CloudFrontLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudFrontLogBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontLogging
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${CloudFrontLogBucket.Arn}/cloudfront/*"
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  AthenaResultBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-athena-results"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteResultsAfter30Days
            Status: Enabled
            ExpirationInDays: 30
            Prefix: cloudfront/
      Tags:
        - Key: project
          Value: !Ref ProjectName

  AthenaResultBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AthenaResultBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAthenaAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - s3:GetBucketLocation
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
            Resource:
              - !Sub "${AthenaResultBucket.Arn}"
              - !Sub "${AthenaResultBucket.Arn}/*"

  CloudFrontLogsDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub "${ProjectName}-cloudfront-logs"
        Description: CloudFront アクセスログ用の Glue データベース

  CloudFrontLogsRawTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref CloudFrontLogsDatabase
      TableInput:
        Name: cloudfront_logs_raw
        Description: CloudFront 標準ログ（TSV, gzip）を読むテーブル
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: cloudfront
          compressionType: gzip
          skip.header.line.count: "2"
          typeOfData: file
        StorageDescriptor:
          Columns:
            - { Name: date, Type: string }
            - { Name: time, Type: string }
            - { Name: x_edge_location, Type: string }
            - { Name: sc_bytes, Type: bigint }
            - { Name: c_ip, Type: string }
            - { Name: cs_method, Type: string }
            - { Name: cs_host, Type: string }
            - { Name: cs_uri_stem, Type: string }
            - { Name: sc_status, Type: int }
            - { Name: cs_referer, Type: string }
            - { Name: cs_user_agent, Type: string }
            - { Name: cs_uri_query, Type: string }
            - { Name: cs_cookie, Type: string }
            - { Name: x_edge_result_type, Type: string }
            - { Name: x_edge_request_id, Type: string }
            - { Name: x_host_header, Type: string }
            - { Name: cs_protocol, Type: string }
            - { Name: cs_bytes, Type: bigint }
            - { Name: time_taken, Type: double }
            - { Name: x_forwarded_for, Type: string }
            - { Name: ssl_protocol, Type: string }
            - { Name: ssl_cipher, Type: string }
            - { Name: x_edge_response_result_type, Type: string }
            - { Name: cs_protocol_version, Type: string }
            - { Name: fle_status, Type: string }
            - { Name: fle_encrypted_fields, Type: string }
            - { Name: c_port, Type: int }
            - { Name: time_to_first_byte, Type: double }
            - { Name: x_edge_detailed_result_type, Type: string }
            - { Name: sc_content_type, Type: string }
            - { Name: sc_content_len, Type: bigint }
            - { Name: sc_range_start, Type: bigint }
            - { Name: sc_range_end, Type: bigint }
          Location: !Sub "s3://${CloudFrontLogBucket}/cloudfront/"
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Compressed: true
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
            Parameters:
              field.delim: "\t"
              serialization.format: "\t"
          StoredAsSubDirectories: false

  CloudFrontAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub "${ProjectName}-cf-workgroup"
      Description: CloudFront ログ分析用 WorkGroup
      RecursiveDeleteOption: true
      State: ENABLED
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: false
        ResultConfiguration:
          OutputLocation: !Sub "s3://${AthenaResultBucket}/cloudfront/"
          EncryptionConfiguration:
            EncryptionOption: SSE_S3

  CloudFrontAthenaDailyInsertRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-cf-athena-insert-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AthenaStartQuery
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                Resource: "*"
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetPartition
                  - glue:GetPartitions
                  - glue:CreateTable
                  - glue:CreatePartition
                  - glue:BatchCreatePartition
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource:
                  - !Sub "${AthenaResultBucket.Arn}"
                  - !Sub "${CloudFrontLogBucket.Arn}"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "${AthenaResultBucket.Arn}/*"
                  - !Sub "${CloudFrontLogBucket.Arn}/cloudfront/*"
                  - !Sub "${CloudFrontLogBucket.Arn}/cloudfront-parquet/*"

  CloudFrontAthenaDailyInsertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../Lambda/src/cloudfront-athena-daily-insert
      FunctionName: !Sub "${ProjectName}-cf-athena-daily-insert"
      Runtime: nodejs22.x
      Handler: index.handler
      Role: !GetAtt CloudFrontAthenaDailyInsertRole.Arn
      Timeout: 300
      Environment:
        Variables:
          WORKGROUP: !Ref CloudFrontAthenaWorkGroup
          DATABASE: !Ref CloudFrontLogsDatabase
          RAW_TABLE: "cloudfront_logs_raw"
          PARQUET_TABLE: "cloudfront_logs_parquet"
          PARQUET_LOCATION: !Sub "s3://${CloudFrontLogBucket}/cloudfront-parquet/"

  CloudFrontAthenaDailyInsertSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: !Sub "${ProjectName}-cf-athena-daily-insert"
      ScheduleExpression: "cron(0 6 * * ? *)"  # 毎日09:00 JST
      ScheduleExpressionTimezone: "Asia/Tokyo"  # JSTタイムゾーン指定
      State: ENABLED
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt CloudFrontAthenaDailyInsertFunction.Arn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn

  SchedulerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt CloudFrontAthenaDailyInsertFunction.Arn

  CloudFrontAthenaDailyInsertPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CloudFrontAthenaDailyInsertFunction
      Principal: scheduler.amazonaws.com
      SourceArn: !GetAtt CloudFrontAthenaDailyInsertSchedule.Arn

  PortfolioAliasRecordA:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFrontDistribution
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref CloudFrontDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  PortfolioAliasRecordAAAA:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFrontDistribution
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref CloudFrontDomainName
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  CloudFrontDistributionIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectName}/edge/cloudfront/distribution-id"
      Type: String
      Value: !Ref CloudFrontDistribution
      Description: !Sub "${ProjectName} edge CloudFront distribution id"
      Tags:
        project: !Ref ProjectName

  CloudFrontDistributionDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectName}/edge/cloudfront/distribution-domain-name"
      Type: String
      Value: !GetAtt CloudFrontDistribution.DomainName
      Description: !Sub "${ProjectName} edge CloudFront distribution domain name"
      Tags:
        project: !Ref ProjectName

Outputs:
  CloudFrontDistributionId:
    Description: CloudFront distribution id
    Value: !Ref CloudFrontDistribution
  CloudFrontDistributionDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
