AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route53 records and failover routing'

Parameters:
  ProjectName:
    Type: String
    Description: Project name (resource prefix)
    Default: "portfolio5352"
  PortfolioRecordName:
    Type: String
    Description: Portfolio FQDN (no trailing dot)
    Default: "portfolio.shou-tech.work"
  HostedZoneId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Route53 hosted zone ID stored in SSM Parameter Store
    Default: "/Route53/hostzone/id"
  PortfolioDistributionDomainName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Portfolio CloudFront distribution domain name stored in SSM Parameter Store
    Default: "/portfolio5352/cloudfront/distribution-domain-name"
  ErrorPageDistributionDomainName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Error page CloudFront distribution domain name stored in SSM Parameter Store
    Default: "/portfolio5352/error/page/cloudfront/distribution-domain-name"
  HealthCheckDomainName:
    Type: String
    Description: Health check target domain name (typically portfolio FQDN)
    Default: "portfolio.shou-tech.work"
  HealthCheckPath:
    Type: String
    Description: Health check path for PRIMARY target
    Default: "/"

Resources:
  PortfolioPrimaryHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        FullyQualifiedDomainName: !Ref HealthCheckDomainName
        ResourcePath: !Ref HealthCheckPath
        Port: 443
        RequestInterval: 30
        FailureThreshold: 3
        EnableSNI: true

  PortfolioPrimaryRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref PortfolioRecordName
      Type: A
      SetIdentifier: "Primary"
      Failover: PRIMARY
      HealthCheckId: !Ref PortfolioPrimaryHealthCheck
      AliasTarget:
        DNSName: !Ref PortfolioDistributionDomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  PortfolioPrimaryRecordAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref PortfolioRecordName
      Type: AAAA
      SetIdentifier: "Primary-ipv6"
      Failover: PRIMARY
      HealthCheckId: !Ref PortfolioPrimaryHealthCheck
      AliasTarget:
        DNSName: !Ref PortfolioDistributionDomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  MaintenanceSecondaryRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref PortfolioRecordName
      Type: A
      SetIdentifier: "Secondary"
      Failover: SECONDARY
      AliasTarget:
        DNSName: !Ref ErrorPageDistributionDomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  MaintenanceSecondaryRecordAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref PortfolioRecordName
      Type: AAAA
      SetIdentifier: "Secondary-ipv6"
      Failover: SECONDARY
      AliasTarget:
        DNSName: !Ref ErrorPageDistributionDomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  FailoverHealthCheckIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectName}/error/failover/route53/healthcheck-id"
      Type: String
      Value: !Ref PortfolioPrimaryHealthCheck
      Description: !Sub "${ProjectName} failover Route53 health check id"
      Tags:
        project: !Ref ProjectName

Outputs:
  HealthCheckId:
    Description: Route53 health check id
    Value: !Ref PortfolioPrimaryHealthCheck
