version: 0.2
env:
  variables:
    test_directory: test/

phases:
  install:
    commands:
      - cd infrastructure/ap-northeast-1/Lambda # go to Lambda directory
      - pwd
      - pip install --upgrade awscli
      - npm install

  pre_build:
    commands:
      - npm test

      # - (cd ${test_directory}; npm test)
  build:
    commands:
      - cd ../ # go back to infrastructure/ap-northeast-1
      - pwd
      - aws cloudformation package --template-file templates/Portfolio.yml --output-template-file portfolio.yml --s3-bucket portfolio-build-bucket-5352 --force-upload

  post_build:
    commands:
      - cd ../../ # go back to root directory
      - pwd

artifacts:
  secondary-artifacts:
    SystemArtifact:
      base-directory: infrastructure/ap-northeast-1/
      files:
        - portfolio.yml
      name: SystemArtifact        

    WebArtifact:
      files:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - next.config.ts
        - tsconfig.json
      name: WebArtifact
