version: 0.2

env:
  variables:
    TARGET_STACK_NAME: ""

phases:
  install:
    commands:
      - echo "Using AWS CLI version"
      - aws --version
  build:
    commands:
      - echo "Preparing CloudFormation stack state for redeploy"
      - |
        set -euo pipefail
        if [ -z "$TARGET_STACK_NAME" ]; then
          echo "TARGET_STACK_NAME environment variable must be set" >&2
          exit 1
        fi
        echo "Checking status of stack: $TARGET_STACK_NAME"
        DESCRIBE_OUTPUT=""
        if ! DESCRIBE_OUTPUT=$(aws cloudformation describe-stacks --stack-name "$TARGET_STACK_NAME" --output json 2>&1); then
          if echo "$DESCRIBE_OUTPUT" | grep -qi "does not exist"; then
            echo "Stack $TARGET_STACK_NAME does not exist. No cleanup required."
            exit 0
          else
            echo "$DESCRIBE_OUTPUT" >&2
            exit 1
          fi
        fi
        STACK_STATUS=$(echo "$DESCRIBE_OUTPUT" | python -c "import sys,json; data=json.load(sys.stdin); print(data['Stacks'][0]['StackStatus'])")
        echo "Current stack status: $STACK_STATUS"
        case "$STACK_STATUS" in
          DELETE_IN_PROGRESS)
            echo "Deletion already in progress. Waiting for completion..."
            aws cloudformation wait stack-delete-complete --stack-name "$TARGET_STACK_NAME"
            ;;
          ROLLBACK_COMPLETE|ROLLBACK_FAILED|DELETE_FAILED|CREATE_FAILED|UPDATE_ROLLBACK_FAILED|UPDATE_ROLLBACK_COMPLETE)
            echo "Stack is in a terminal rollback/failed state. Deleting before redeploy..."
            aws cloudformation delete-stack --stack-name "$TARGET_STACK_NAME"
            echo "Waiting for stack deletion to finish..."
            aws cloudformation wait stack-delete-complete --stack-name "$TARGET_STACK_NAME"
            echo "Stack $TARGET_STACK_NAME deleted successfully."
            ;;
          *)
            echo "Stack $TARGET_STACK_NAME is in status $STACK_STATUS. No action required."
            ;;
        esac
artifacts:
  files:
    - '**/*'
  discard-paths: yes
