version: 0.2
phases:
  install:
    commands:
      - cd infrastructure/ap-northeast-1/Lambda # go to Lambda directory
      - pwd
      - pip install --upgrade awscli
      - npm install

  pre_build:
    commands:
      - npm test

  build:
    commands:
      - cd ../ # go back to infrastructure/ap-northeast-1
      - pwd
      - aws cloudformation package --template-file templates/portfolio-backend.yml --output-template-file templates/portfolio-backend.packaged.yml --s3-bucket portfolio-build-bucket-5352 --force-upload
      - ls -la templates

  post_build:
    commands:
      - cd ../../ # go back to root directory
      - cp frontend/buildspec/buildspec-nextjs.yml frontend/buildspec-nextjs.yml
      - pwd

artifacts:
  secondary-artifacts:
    SystemArtifact:
      base-directory: infrastructure/ap-northeast-1/templates
      files:
        - portfolio-frontend.yml
        - portfolio-backend.packaged.yml
      name: SystemArtifact        

    WebArtifact:
      base-directory: frontend
      files:
        - '**/*'
      name: WebArtifact

    DataArtifact:
      base-directory: infrastructure/ap-northeast-1
      files:
        - 'buildspec/buildspec-seed-projects.yml'
        - 'scripts/tsconfig.seed.json'
        - 'scripts/seed-projects.ts'
        - 'scripts/package.json'
        - 'scripts/package-lock.json'
        - 'data/ProjectData.ts'
      discard-paths: no
      name: DataArtifact

    CleanupCfnArtifact:
      base-directory: infrastructure/ap-northeast-1/
      files:
        - 'buildspec/buildspec-pre-cfn.yml'
      discard-paths: yes
      name: CleanupCfnArtifact