version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing AWS CLI if needed..."
      - pip install --upgrade awscli
      - yum install -y jq

  build:
    commands:
      - echo "=== us-east-1 WAF ARNをDeployOutput/output.jsonから取得しEventBridge通知 ==="
      - |
        # EventBridgeでap-northeast-1に通知
        echo "=== ap-northeast-1へEventBridgeイベント通知 ==="
        aws events put-events --region ap-northeast-1 \
          --entries '[
            {
              "Source": "custom.waf-pipeline",
              "DetailType": "WAFDeployComplete",
              "Detail": "{\"status\": \"SUCCEEDED\"}",
              "EventBusName": "portfolio-waf-deploy-success-notify-from-us-east-1"
            }
          ]'
