version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing AWS CLI if needed..."
      - pip install --upgrade awscli

      - echo "=== ワークスペース全体の構造 ==="
      - ls -lR .
      - echo "=== /codebuild/output配下の構造 ==="
      - ls -lR /codebuild/output || true

      - chmod +x infrastructure/us-east-1/scripts/put-waf-arn-to-ssm.sh
  build:
    commands:

      - echo "=== us-east-1 WAF ARNをoutput.jsonから取得しSSMに格納 ==="
      - |
        OUTPUT_JSON=$(find /codebuild/output -type f -name 'output.json' | head -n 1)
        if [ -z "$OUTPUT_JSON" ]; then
          echo "output.jsonが見つかりませんでした。" >&2
          exit 1
        fi
        echo "output.jsonのパス: $OUTPUT_JSON"
        WAF_ARN=$(jq -r '.Stacks[0].Outputs[] | select(.OutputKey=="WebAclArn") | .OutputValue' "$OUTPUT_JSON")
        if [ -z "$WAF_ARN" ]; then
          echo "WAF ARNが$output.jsonから取得できませんでした。" >&2
          exit 1
        fi
        echo "取得したWAF ARN: $WAF_ARN"
        ./infrastructure/us-east-1/scripts/put-waf-arn-to-ssm.sh "$WAF_ARN"

      # EventBridgeでap-northeast-1に通知
      - echo "=== ap-northeast-1へEventBridgeイベント通知 ==="
      - |
        aws events put-events --region ap-northeast-1 --entries '[
          {
            "Source": "custom.waf-pipeline",
            "DetailType": "WAFDeployComplete",
            "Detail": "{\"status\": \"SUCCEEDED\", \"wafArn\": \"'$WAF_ARN'\"}"
          }
        ]'

artifacts:
  files:
    - '**/*'
