version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing AWS CLI if needed..."
      - pip install --upgrade awscli
      - yum install -y jq

      - echo "カレントディレクトリ"
      - ls -l .

      - echo "親ディレクトリ"
      - ls -lR ..

      - echo "output.jsonを表示"
      - cat ../01/output.json
  build:
    commands:
      - echo "=== us-east-1 WAF ARNをDeployOutput/output.jsonから取得しSSMに格納 ==="
      - |
        WAF_ARN=$(jq -r '.WebACLArn' ../01/output.json)
        if [ -z "$WAF_ARN" ]; then
          echo "WAF ARNが../01/output.jsonから取得できませんでした。" >&2
          exit 1
        fi
        echo "取得したWAF ARN: $WAF_ARN"
        # SSM Parameter Storeに格納（overwrite有効）
        aws ssm put-parameter \
          --region us-east-1 \
          --name "/portfolio/waf/arn" \
          --type String \
          --value "$WAF_ARN" \
          --overwrite
        echo "WAF ARNをSSM Parameter Storeに格納しました: $WAF_ARN"
        
      # EventBridgeでap-northeast-1に通知
      - echo "=== ap-northeast-1へEventBridgeイベント通知 ==="
      - |
        aws events put-events --region ap-northeast-1 \
          --entries '[
            {
              "Source": "custom.waf-pipeline",
              "DetailType": "WAFDeployComplete",
              "Detail": "{\"status\": \"SUCCEEDED\", \"wafArn\": \"'$WAF_ARN'\"}",
              "EventBusName": "portfolio-waf-deploy-success-notify-from-us-east-1"
            }
          ]'

artifacts:
  files:
    - '**/*'
