version: 0.2

env:
  parameter-store:
    DEPLOY_S3_BUCKET: /portfolio5352/s3/static-site-bucket-name
  variables:
    CLOUDFRONT_DISTRIBUTION_ID_SSM_PATH_PRIMARY: /portfolio5352/edge/cloudfront/distribution-id

phases:
  install:
    commands:
      - echo "Preparing to deploy static artifacts"
      - |
        if [ -z "$DEPLOY_S3_BUCKET" ]; then
          echo "DEPLOY_S3_BUCKET environment variable is required." >&2
          exit 1
        fi
      - |
        if [ -z "${CLOUDFRONT_DISTRIBUTION_ID:-}" ]; then
          echo "Resolving CloudFront distribution id from SSM (optional)"
          CLOUDFRONT_DISTRIBUTION_ID=$(
            aws ssm get-parameter \
              --name "$CLOUDFRONT_DISTRIBUTION_ID_SSM_PATH_PRIMARY" \
              --query 'Parameter.Value' \
              --output text 2>/dev/null || true
          )

          if [ -z "${CLOUDFRONT_DISTRIBUTION_ID:-}" ] || [ "${CLOUDFRONT_DISTRIBUTION_ID}" = "None" ]; then
            unset CLOUDFRONT_DISTRIBUTION_ID
            echo "CloudFront distribution id not found; CloudFront invalidation will be skipped."
          else
            echo "CloudFront distribution id resolved."
          fi
        fi
      - |
        if [ ! -d "out" ]; then
          echo "Expected static output directory 'out' was not found in artifact." >&2
          exit 1
        fi
  build:
    commands:
      - echo "No build step required - using provided artifact"
  post_build:
    commands:
      - echo "Syncing static output to s3://${DEPLOY_S3_BUCKET}"
      - aws s3 sync out/ "s3://${DEPLOY_S3_BUCKET}" --delete
      - echo "Creating aliases for directory index files"
      - |
        find out -type f -name "index.html" -print0 | while IFS= read -r -d '' file; do
          key=${file#out/}
          dirKey=${key%index.html}
          if [ -n "$dirKey" ]; then
            normalizedKey=${dirKey%/}/
            echo "Publishing alias ${normalizedKey} with text/html"
            aws s3api put-object --bucket "$DEPLOY_S3_BUCKET" --key "${normalizedKey}" --body "$file" --content-type "text/html"
          fi
        done
      - echo "Ensuring extensionless HTML objects have text/html content-type"
      - |
        find out -type f ! -name "*.*" -print0 | while IFS= read -r -d '' file; do
          key=${file#out/}
          echo "Re-uploading ${key} with text/html"
          aws s3 cp "$file" "s3://${DEPLOY_S3_BUCKET}/${key}" --content-type "text/html"
        done
      - |
        if [ -n "${CLOUDFRONT_DISTRIBUTION_ID:-}" ]; then
          echo "Creating CloudFront invalidation for distribution ${CLOUDFRONT_DISTRIBUTION_ID}"
          aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"
        else
          echo "Skipping CloudFront invalidation (no distribution id available)."
        fi

artifacts:
  files:
    - '**/*'
  base-directory: out
