version: 0.2

phases:
  install:
    commands:
      - echo "Preparing to sync pre-built static assets"
      - ls
  build:
    commands:
      - echo "No build step required - using provided artifact"
  post_build:
    commands:
      - echo "Syncing static output to S3"
      - aws s3 sync out/ s3://portfolio-static-site --delete

artifacts:
  files:
    - '**/*'
  base-directory: out
