AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route53 failover (PRIMARY/SECONDARY) for maintenance domain'

Parameters:
  ProjectName:
    Type: String
    Description: Project name (resource prefix)
    Default: "portfolio5352"
  Route53RecordName:
    Type: String
    Description: FQDN for the record (no trailing dot)
    Default: "maintenance.shou-tech.work"
  HostedZoneId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Route53 hosted zone ID stored in SSM Parameter Store
    Default: "/Route53/hostzone/id"
  PrimaryDistributionDomainName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: CloudFront distribution domain name (PRIMARY), stored in SSM Parameter Store
    Default: "/portfolio5352/cloudfront/distribution-domain-name"
  SecondaryDistributionDomainName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: CloudFront distribution domain name (SECONDARY), stored in SSM Parameter Store
    Default: "/portfolio5352/error/page/cloudfront/distribution-domain-name"
  HealthCheckPath:
    Type: String
    Description: Health check path for PRIMARY target
    Default: "/"

Resources:
  PortfolioPrimaryHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        FullyQualifiedDomainName: !Ref Route53RecordName
        ResourcePath: !Ref HealthCheckPath
        Port: 443
        RequestInterval: 30
        FailureThreshold: 3
        EnableSNI: true

  PrimaryRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Route53RecordName
      Type: A
      SetIdentifier: "Primary"
      Failover: PRIMARY
      HealthCheckId: !Ref PortfolioPrimaryHealthCheck
      AliasTarget:
        DNSName: !Ref PrimaryDistributionDomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  PrimaryRecordAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Route53RecordName
      Type: AAAA
      SetIdentifier: "Primary-ipv6"
      Failover: PRIMARY
      HealthCheckId: !Ref PortfolioPrimaryHealthCheck
      AliasTarget:
        DNSName: !Ref PrimaryDistributionDomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  SecondaryRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Route53RecordName
      Type: A
      SetIdentifier: "Secondary"
      Failover: SECONDARY
      AliasTarget:
        DNSName: !Ref SecondaryDistributionDomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  SecondaryRecordAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Route53RecordName
      Type: AAAA
      SetIdentifier: "Secondary-ipv6"
      Failover: SECONDARY
      AliasTarget:
        DNSName: !Ref SecondaryDistributionDomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  FailoverHealthCheckIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectName}/error/failover/route53/healthcheck-id"
      Type: String
      Value: !Ref PortfolioPrimaryHealthCheck
      Description: !Sub "${ProjectName} failover Route53 health check id"
      Tags:
        project: !Ref ProjectName

Outputs:
  HealthCheckId:
    Description: Route53 health check id
    Value: !Ref PortfolioPrimaryHealthCheck

