AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CodePipeline definition for the ap-northeast-1 portfolio deployment. This template
  mirrors the current pipeline configuration exported on 2025-11-03 and expects
  pre-existing CodeBuild projects, IAM roles, and CodeStar connections.

Parameters:
  PipelineName:
    Type: String
    Default: portfolio
    Description: Name of the pipeline.
  ArtifactBucketName:
    Type: String
    Description: S3 bucket used by CodePipeline to store artifacts.
  CodePipelineServiceRoleArn:
    Type: String
    Description: IAM role ARN assumed by the pipeline.
  CodeStarConnectionArn:
    Type: String
    Description: CodeStar Connections ARN for the GitHub repository.
  RepositoryId:
    Type: String
    Default: GitShou/portfolio
    Description: GitHub repository in the form owner/repo.
  BranchName:
    Type: String
    Default: main
    Description: Git branch to track.
  CodeBuildProjectName:
    Type: String
    Default: portfolio-build
    Description: CodeBuild project used for all build actions.
  CloudFormationDeploymentRoleArn:
    Type: String
    Description: IAM role ARN assumed by CloudFormation deploy actions.
  BackendStackName:
    Type: String
    Default: Portfolio-Stack-backend
    Description: CloudFormation stack name for backend resources.
  FrontendStackName:
    Type: String
    Default: Portfolio-Stack-frontend
    Description: CloudFormation stack name for frontend resources.

Resources:
  PortfolioPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: !Ref CodePipelineServiceRoleArn
      PipelineType: V2
      ExecutionMode: QUEUED
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucketName
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              Namespace: SourceVariables
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                BranchName: !Ref BranchName
                ConnectionArn: !Ref CodeStarConnectionArn
                DetectChanges: "false"
                FullRepositoryId: !Ref RepositoryId
                OutputArtifactFormat: CODE_ZIP
              RunOrder: 1
        - Name: Deploy-AWS-Resources
          Actions:
            - Name: build-template
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: SystemArtifact
                - Name: WebArtifact
                - Name: DataArtifact
                - Name: CleanupCfnArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
                BuildspecOverride: infrastructure/ap-northeast-1/buildspec/buildspec-cfn.yml
              RunOrder: 1
            - Name: cleanup-cfn-backend
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: CleanupCfnArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
                BuildspecOverride: buildspec-pre-cfn.yml
                EnvironmentVariables: !Sub |
                  [{"name":"TARGET_STACK_NAME","value":"${BackendStackName}","type":"PLAINTEXT"}]
              RunOrder: 2
            - Name: cleanup-cfn-frontend
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: CleanupCfnArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
                BuildspecOverride: buildspec-pre-cfn.yml
                EnvironmentVariables: !Sub |
                  [{"name":"TARGET_STACK_NAME","value":"${FrontendStackName}","type":"PLAINTEXT"}]
              RunOrder: 2
            - Name: deploy-backend
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: SystemArtifact
              OutputArtifacts:
                - Name: deployed-aws-resources
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !Ref CloudFormationDeploymentRoleArn
                StackName: !Ref BackendStackName
                TemplatePath: SystemArtifact::portfolio-backend.packaged.yml
              RunOrder: 3
            - Name: deploy-frontend-system
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: SystemArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !Ref CloudFormationDeploymentRoleArn
                StackName: !Ref FrontendStackName
                TemplatePath: SystemArtifact::portfolio-frontend.yml
              RunOrder: 3
        - Name: Build
          Actions:
            - Name: deploy-projects-data-to-ddb
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: DataArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
                BuildspecOverride: buildspec/buildspec-seed-projects.yml
              RunOrder: 1
            - Name: build-next-js
              Namespace: BuildVariables
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: WebArtifact
              OutputArtifacts:
                - Name: WebContents
                - Name: TestResults
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
                BuildspecOverride: buildspec-nextjs.yml
              RunOrder: 2
            - Name: deploy-contents
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: WebContents
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
                BuildspecOverride: buildspec-deploy-contents.yml
              RunOrder: 3
