version: 0.2
phases:
	install:
		commands:
			- npm install
	build:
		commands:
			- npm run build
			- npm run export
	post_build:
		commands:
			- aws s3 sync ./out s3://portfolio-static-site --delete

artifacts:
	files:
		- out/**
