AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudFront用WAFv2 WebACLおよびLambda@Edgeリソース（us-east-1専用）

Parameters:
  WebAclName:
    Type: String
    Default: portfolio-cloudfront-waf
    Description: WebACL名
  ProjectName:
    Type: String
    Default: "portfolio5352"
    Description: プロジェクト名（リソース名のプレフィックス）
  ViewerRequestFunctionName:
    Type: String
    Default: "portfolio5352-vwrw"
    Description: Lambda@Edge viewer-request 関数名（64文字以内を推奨）

Resources:
  CloudFrontWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Ref WebAclName
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Ref WebAclName
      Rules: []  # 必要に応じてルールを追加
      Tags:
        - Key: project
          Value: !Ref ProjectName

  ViewerRequestRewriteFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: project
          Value: !Ref ProjectName

  ViewerRequestRewriteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref ViewerRequestFunctionName
      Description: CloudFront viewer-request Lambda@Edge function that rewrites clean URLs to index.html
      CodeUri: ../Lambda/src/cloudfront-viewer-request/
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 5
      Role: !GetAtt ViewerRequestRewriteFunctionRole.Arn
      Tags:
        project: !Ref ProjectName

  ViewerRequestRewriteFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref ViewerRequestRewriteFunction
      Description: !Sub "${ProjectName} viewer-request auto-versioned ${AWS::StackName}-${AWS::Region}"
    DependsOn:
      - ViewerRequestRewriteFunction
      
  ViewerRequestRewritePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:GetFunction
      FunctionName: !Ref ViewerRequestRewriteFunctionVersion
      Principal: edgelambda.amazonaws.com

Outputs:
  WebACLArn:
    Value: !GetAtt CloudFrontWebACL.Arn
    Description: CloudFront用WAF WebACLのARN（CloudFrontのWebACLIdに指定）

  VRRFVersionParameterARN:
    Value: !Ref ViewerRequestRewriteFunctionVersion
    Description: CloudFront viewer-request Lambda@Edge関数バージョンARN
